name: Release Internal

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version (x.x.x)'
        required: true

jobs:
  createrelease:
    name: Build release app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Bump android version
        run: bash ./gradlew bumpVersion --newVersionName ${{ github.event.inputs.versionName }}

      - name: Build release APK
        run: bash ./gradlew bundleRelease

      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        id: release_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: kiwi-${{ github.event.inputs.versionName }}
          path: ${{steps.release_app.outputs.signedReleaseFile}}

      - name: Commit version update
        run: |
          git add versions.properties
          git commit -m "Prepare release ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new release branch
        run: git push origin release/v${{ github.event.inputs.versionName }}

      - name: Create pull request into develop
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop

      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: master
          title: v${{ github.event.inputs.versionName }} into master

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (INTERNAL)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: pl.jutupe.kiwi
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: internal

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been released on google play.'