name: Release Internal

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version (x.x.x)'
        required: true

jobs:
  setup-release:
    name: Setup release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Bump android version
        run: bash ./gradlew bumpVersion --newVersionName ${{ github.event.inputs.versionName }}

      - name: Commit version update
        run: |
          git add versions.properties
          git commit -m "Prepare release ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new release branch
        run: git push origin release/v${{ github.event.inputs.versionName }}

  build-aab:
    name: Build release .aab
    runs-on: ubuntu-latest
    needs: setup-release

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/v${{ github.event.inputs.versionName }}

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build release AAB
        run: bash ./gradlew bundleRelease

      - name: Sign release AAB
        uses: r0adkll/sign-android-release@v1
        id: release_aab
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: kiwi_aab
          path: ${{steps.release_aab.outputs.signedReleaseFile}}

  build-apk:
    name: Build release .apk
    runs-on: ubuntu-latest
    needs: setup-release

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/v${{ github.event.inputs.versionName }}

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        id: release_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: kiwi_apk
          path: ${{steps.release_apk.outputs.signedReleaseFile}}

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-aab, build-apk]

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/v${{ github.event.inputs.versionName }}

      - name: Create git tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          custom_tag: ${{ github.event.inputs.versionName }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download apk artifact
        uses: actions/download-artifact@v2
        with:
          name: kiwi_apk
          path: artifacts/

      - name: Download aab artifact
        uses: actions/download-artifact@v2
        with:
          name: kiwi_aab
          path: artifacts/

      - name: Create git release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request into develop
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop

      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: master
          title: v${{ github.event.inputs.versionName }} into master

  release:
    name: Release app on google play
    runs-on: ubuntu-latest
    needs: [create-release]

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: release/v${{ github.event.inputs.versionName }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Download aab artifact
        uses: actions/download-artifact@v2
        with:
          name: kiwi_aab
          path: artifacts/

      - name: Deploy to Play Store (INTERNAL)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: pl.jutupe.kiwi
          releaseFiles: |
            artifacts/*
          track: internal

  notify-release:
    name: Notify about release
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been released on google play.'